---
title: "Introduction ✨ "
execute:
    eval: true
    echo: false
---

## What the course will look like

We will work together through developing a package, and at various steps along the way we will take detours to examine tools, processes, and package structure.

The tools we'll be using (RStudio + devtools, usethis, and friends) are designed to 'get out of the way' and enable a workflow that helps you focus on the code you are writing.
We'll be live coding together, and emphasizing these workflows and processes.

The core ideas in this course are taken from the [R Packages](https://r-pkgs.org) book [@wickham2023r] by Hadley Wickham and Jenny Bryan, now in its second edition.
We basically follow the format of the "Whole Game" chapter, stepping through the key steps in making a package, with detours along the way to explore the main concepts in a bit more detail.

### About this website

This site is meant to be supplemental to the in-class activities.
The slides are [available in pdf form](materials/slides.pdf).
The modules contain the code that we wrote in the workshop, with very little explanation or annotation.
This is intentional - for a self-guided walk-through of package development, I recommend reading the [R Packages](https://r-pkgs.org) book.

## Course logistics

### Code of Conduct

Please note that all participants must abide by the [Code of Conduct](https://www.contributor-covenant.org/version/2/1/code_of_conduct/).
We are committed to providing a professional, friendly and safe environment for all participants at its events, regardless of gender, sexual orientation, disability, race, ethnicity, religion, national origin or other protected class.

### Schedule

```{r}
library(readr)
library(gt)
schedule <- read_csv("data/schedule.csv", col_types = "Dccc")

gt(schedule, groupname_col = "Date", rowname_col = "Time (PST)")
```

### References

::: {#refs}
:::
